### ISSUE TITLE
Build broken tag 5.0.1

### ISSUE THREAD

**Issue by killingthemthistime** [linuxdeepin/dde-network-utils#13]
so far as I can tell there is a wireup issue, after someone renamed someting and then tagged it for release. not using qt at all personally, just trying to get a working build of the desktop environment going.  it would appear someone just changed an event name and didn't update the wireup code.  anyway it results in this error. It looks like in the derived interface that the StateChanged signal is what one is looking for. but have not really looked into this that closely yet.  more if I get it working.

```
networkworker.cpp: In constructor ‘dde::network::NetworkWorker::NetworkWorker(dde::network::NetworkModel*, QObject*)’:
networkworker.cpp:41:45: error: ‘ConnectivityChanged’ is not a member of ‘dde::network::NetworkInter’ {aka ‘__Network’}
     connect(&m_networkInter, &NetworkInter::ConnectivityChanged, m_networkModel, &NetworkModel::onConnectivityChanged);
                                             ^~~~~~~~~~~~~~~~~~~
networkworker.cpp: In member function ‘void dde::network::NetworkWorker::active()’:
networkworker.cpp:73:58: error: ‘using NetworkInter = com::deepin::daemon::Network’ {aka ‘class __Network’} has no member named ‘connectivity’; did you mean ‘connections’?
     m_networkModel->onConnectivityChanged(m_networkInter.connectivity());
                                                          ^~~~~~~~~~~~
                                                          connections
make[1]: *** [Makefile:505: networkworker.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/john/deepinsource/dde-network-utils-5.0.1'
dh_auto_build: make -j4 returned exit code 2
make: *** [debian/rules:7: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by BLumia** [comment]
Which distro are you using?

**Comment by killingthemthistime** [comment]
Doesnt seem to matter as this is a code issue.

But, Ubuntu.

**Comment by BLumia** [comment]
I though your distro had vendored the package  :/

Just did a quick test with a normal `qmake` and `make` process under Deepin and it compiles as expected. Maybe you are missing some depts like `libdframeworkdbus-dev` (as a part of [dde-qt-dbus-factory](https://github.com/linuxdeepin/dde-qt-dbus-factory))?

**Comment by yangxuan8282** [comment]
I got same issues on other distros. 
Then I found my `deepin-qt-dbus-factory-devel` (which should equal to `libdframeworkdbus-dev`) is too old, which is download from repos.
After build latest version `deepin-qt-dbus-factory-devel`, the build success.

**Comment by killingthemthistime** [comment]
For sh**ts and giggles I'll try rebuilding.
I did a trace through the code it was complaining about though. Though not an incredibly deep one.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BLumia** [comment]
`error: ‘using NetworkInter = com::deepin::daemon::Network’ {aka ‘class __Network’} has no member named ‘connectivity’;`

Normally when this sort of error happens in a released tag version package, it most likely a package dept issue..
