### ISSUE TITLE
Not connecting to wi-fi after upgrade to Fedora 31

### ISSUE THREAD

**Issue by bocekm** [linuxdeepin/dde-network-utils#14]
deepin-network-utils-5.0.1-1.fc31.x86_64
NetworkManager-wifi-1.20.6-1.fc31.x86_64

Connecting to a wireless network is in a loop - failing and trying again endlessly.

I'm seeing the same as _scybhe_ in: https://bbs.archlinux.org/viewtopic.php?id=248406
Namely, in journal:
```
daemon/network[803]: manager_device.go:192: Failed to re-active connection: No such interface “org.freedesktop.DBus.Properties” on object at path /
wpa_supplicant[599]: dbus: wpa_dbus_property_changed: no property SessionLength in object /fi/w1/wpa_supplicant1/Interfaces/0
```

When switching to GNOME, connecting to wireless works without a problem.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
