### ISSUE TITLE
Network crashing 

### ISSUE THREAD

**Issue by sdlins** [linuxdeepin/dde-network-utils#2]
Hi,
My network connection (wireless) is crashing suddenly, sometimes I am not even using a browser, I am just reading something. The system show the message that "The device was removed". After the crash, the icon shows a "disconnected" network but in configs I can't see the wireless connection anymore (please, see the video below).

There is no way to recover it. Even if I try logout/login again. The only way is RESTART the computer (yeah, very frustrating).

I am here If you need more information. Hope it to be solved because we like deepin so much. Thank you.

PS: Deepin 15.7 / Two users (accounts) / My cabled network is always left disabled since I dont use it. / This problem happens about once two days.

[Video showing just after crashing and icon, some dmesg and commands trying put network up again](https://github.com/linuxdeepin/dde-network-utils/files/2329689/deepin-screen-recorder_Select.area_20180828162942.mp4.tar.gz)

**Comment by slinstj** [comment]
Hello! There's somebody over there?

**Comment by Tehmal** [comment]
Same problem
I get network UPC/Redmi disconnected
im using LTE modem plus and play from ZTE.

**Comment by listenerri** [comment]
Hi, looks like the fireware of the driver can not load correctly when restart NetworkManager, you can excute the follow command to ensure you network card has been managed by NetworkManager:
```
nmcli device
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
