### ISSUE TITLE
wifi disconnected after suspend

### ISSUE THREAD

**Issue by cupliz** [linuxdeepin/dde-network-utils#3]
Hello, recently i tried deepin and its very nice but i got a little bug. Wifi is disconnected when i suspend the laptop after lid close or suspend button.

Here is what i've done, but unfortunately it does not work.
1. Restart network-manager and networking service
2. Adding script under system-sleep that re-install and restart the driver

```
$ nmcli dev wifi
IN-USE  SSID  MODE  CHAN  RATE  SIGNAL  BARS  SECURITY 
$ journalctl -kb
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Sun 2018-10-07 05:48:37 WIB, end at Thu 2018-10-18 14:11:04 WIB. --
-- No entries --
```

**Comment by listenerri** [comment]
Hello, i think you can try to upgrade you wireless driver to fix it.

**Comment by DasJott** [comment]
Same Problem here. It keeps on trying to connect to a well known wifi network but also keeps failing and then tries again...
Sometimes after half aroudn half an hour it finaly manages to connect.

Where does it fail??

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
